export const links = {
  prime: "https://primefaces.org/primereact"
}

export const I18N_PREFIX = "stories.concept"

export const unusedComponents = [
  "AutoComplete",
  "CascadeSelect",
  "ColorPicker",
  "Editor",
  "Mention",
  "Knob",
  "Rating",
  "ListBox",
  "Accordion",
  "AccordionTab",
  "MultiStateCheckbox",
  "SplitButton",
  "SpeedDial",
  "ToggleButton",
  "DataView",
  "OrderList",
  "OrganizationChart",
  "GMap",
  "Paginator",
  "ContextMenu",
  "PickList",
  "Menubar",
  "Timeline",
  "Toolbar",
  "DeferredContent",
  "Menu",
  "TabMenu",
  "SlideMenu",
  "MegaMenu",
  "Sidebar",
  "Steps",
  "Dock",
  "Chart",
  "Carousel",
  "Galleria",
  "Inplace",
  "Ripple",
  "Captcha",
  "Terminal",
  "OverlayPanel",
  "StyleClass",
  "ScrollPanel",
  "Splitter",
  "Panel",
  "Fieldset",
  "TreeTable",
  "VirtualScroller",
  "DataScroller",
  "TreeSelect",
  "Slider",
  "Password",
  "ListBox",
  "ProgressSpinner",
  "Tree",
]
