name: CI

on:
  pull_request:

jobs:
  storybook-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Run build
        run: |
          yarn install --frozen-lockfile
          cd storybook
          yarn install --frozen-lockfile
          yarn build-storybook

  storybook-lints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run lints
        run: |
          yarn install --frozen-lockfile
          cd storybook
          yarn install --frozen-lockfile
          yarn lint

  sphere:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}

      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn lint
